### ISSUE TITLE
LaTeX Warning: Unused global option(s): [DIV=10,BCOR=10mm]

### ISSUE THREAD

**Issue by Sparklester** [Pseudomanifold/latex-mimosis#13] opened 2020-07-20 15:54 UTC
Could it be that the options DIV and BCOR from the scrbook package are now deprecated?

**How to replicate this warning:**
Clone the repo and build.

**Comment by Pseudomanifold** [comment] 2020-07-23 07:46
That's strange! I cannot reproduce this problem locally (using TeXLive 2020). Which distribution are you using?

**Comment by Sparklester** [comment] 2020-07-23 16:35
I am using MiKTeX 20.6.29 on a Windows 10 machine. 

Doesn't seem to be a build specific issue, since it persists with both pdfLaTeX and XeLaTeX.
As with any other _Unused global options_ warning, it goes away if the specified options are mentioned in the `documentclass` command.

**Comment by Pseudomanifold** [comment] 2020-07-25 19:55
Thanks, this is fixed now! The options have to be provided in a different way. The warnings should now disappear; please reopen the issue if this is not the case.

**Closed by Pseudomanifold** 2020-07-25 19:55 UTC
